### ISSUE TITLE
Range propagation fails to propagate the value of the parameter

### ISSUE THREAD

**Issue by parinaz2015** [akshay9594/The-Cetus-Project#15]
int main()
{
    int x=3000;
    shift(x);
    return 0;
}
void shift(int d){
  double a[1000000];
  int j = 0 ,sum=0, n = 1000000;
  for (j = 0; j < n; j++) {
    a[j] = j + 1000;
    sum=sum+a[j];
  }
  for (j = 0; j < n; j++) {
    a[j] = a[d+j];
  }
    return;
}  

This example shows that range propagation fails to propagate the value of **d** to function **shift**.

**Comment by akshay9594** [comment]
Enable Inter-procedural range propagation by setting "-range" option in Cetus to 2.
